Attribute VB_Name = "mod_Constants"
Global Const CON_SUCCESS = "连接成功!" & vbNewLine
Global Const CON_FAILURE = "连接失败!" & vbNewLine
Global Const RECON_SUCCESS = "重新连接成功!" & vbNewLine
Global Const MODEM_INFO = "Modem拨号信息"
Global Const MODEM_NUMBER = "电话号码"
Global Const MODEM_USER = "用户名"
Global Const MODEM_PASS = "密码"
Global Const SERVER_INFO = "服务器信息"
Global Const SERVER_A = "服务器A"
Global Const SERVER_USER_A = "用户名A"
Global Const SERVER_PASS_A = "口令A"
Global Const SERVER_TABLE_A = "数据表A"
Global Const SERVER_TIMESTAMP_A = "初始发送时间A"
Global Const SERVER_B = "服务器B"
Global Const SERVER_USER_B = "用户名B"
Global Const SERVER_PASS_B = "口令B"
Global Const SERVER_TABLE_B = "数据表B"
Global Const SERVER_TIMESTAMP_B = "初始发送时间B"
Global Const CONNECT_INFO = "连接信息"
Global Const CONNECT_IP = "连接IP"
Global Const CONNECT_PORT = "连接端口"

Global Const LISTEN_SUCCESS = "端口侦听成功！"
Global Const LISTEN_FAILURE = "端口侦听失败！"
Global Const LISTEN_CLOSED = "端口侦听结束！"

Global Const BTN_CONNECT = "连接有线网络"
Global Const BTN_DISCONN = "断开有线网络"
Global Const BTN_START = "开始接收"
Global Const BTN_STOP = "停止接收"
Global Const BTN_PREF = "关于"
Global Const BTN_QUIT = "退出程序"

Global Const NAME_MODEM = "Modem"
Global Const NAME_ADSL = "adsl"
Global Const NAME_VPN = "VPN"
Global Const NAME_CDMA1X = "CDMA1X"
